Repository Jungminchae/orm-study, pull requests merged in 2024-07, with the labels that each got.

#14 자료형 객관식 3문제, 변수 객관식 4문제 추가
  orm_study/quiz/python/변수/multiple_choice.txt
  orm_study/quiz/python/자료형/multiple_choice.txt
Labels: 문제추가

#18 오류 수정, 객관식 선지 수정
  orm_study/quiz/command.py
  orm_study/quiz/python/변수/multiple_choice.txt
Labels: bug

#20 파이썬 문제추가 - 자료형 완료
  orm_study/quiz/python/자료형/multiple_choice.txt
Labels: 문제추가

#29 Add test and some of documentation
  CONTRIBUTING.md
  README.md
  TODO.md
  tests/test_quiz_constants.py
Labels: documentation

#25 💬 Upload 연산 part and add a new sheet
  orm_study/quiz/python/연산자/multiple_choice.txt
Labels: 문제추가

#31 add 파이썬 변수, 연산자, 자료형 퀴즈
  orm_study/quiz/python/변수/multiple_choice.txt
  orm_study/quiz/python/연산자/multiple_choice.txt
  orm_study/quiz/python/자료형/multiple_choice.txt
Labels: 문제추가

#33 Add 주관식 문제 추가
  TODO.md
  orm_study/quiz/command.py
  orm_study/quiz/python/변수/subjective.txt
  orm_study/quiz/reader.py
Labels: 문제추가, 기능추가

#35 add python quiz module
  TODO.md
  orm_study/quiz/_python/변수/multiple_choice.txt
  orm_study/quiz/_python/변수/subjective.txt
  orm_study/quiz/_python/연산자/multiple_choice.txt
  orm_study/quiz/_python/자료형/multiple_choice.txt
  orm_study/quiz/python.py
  orm_study/quiz/reader.py
  tests/conftest.py
  tests/test_quiz_command.py
  tests/test_quiz_constants.py
  tests/test_quiz_python.py
Labels: 기능추가

#39 add 챕터4 조건문 객관식 10문제
  TODO.md
  orm_study/quiz/_python/조건문/multiple_choice.txt
  orm_study/quiz/constants.py
Labels: 문제추가

#40 Change linter to Ruff
  .flake8
  .github/workflows/03-ci.yml
  .pre-commit-config.yaml
  orm_study/main.py
  orm_study/quiz/certification.py
  orm_study/quiz/command.py
  orm_study/quiz/python.py
  orm_study/quiz/reader.py
  pyproject.toml
  scripts/quiz_format_checker.py
  tests/conftest.py
  tests/test_quiz_command.py
  tests/test_quiz_constants.py
  tests/test_quiz_python.py
Labels: 수정, chore
